server:
  port: 8079
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springData
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

